function vertical_Structure_of_Selected_Characteristics_for_Mentioned_Instantaneous_Elementes_of_Mentioned_Single_sub_Region = FC_FingerPrint_for_each_sub_Region (  input_Single_sub_Region,                                                                           ... used here
                                                                                                                                                                                                                                                               vertical_Structure_of_IQ_Component_Parameters,                                        ... used here
                                                                                                                                                                                                                                                               ...
                                                                                                                                                                                                                                                               vertical_Cell_of_Instantaneous_Elements_Names,                                        ... used in: Instantaneous_Element_Extractor / selected_Instantaneous_Element_Function 
                                                                                                                                                                                                                                                               vertical_Cell_of_Characteristics_Names,                                                      ... used in: Instantaneous_Element_Extractor / selected_Instantaneous_Element_Function 
                                                                                                                                                                                                                                                               device_Index,                                                                                             ...
                                                                                                                                                                                                                                                               fingerPrint_Index,                                                                                       ...
                                                                                                                                                                                                                                                               sub_Region_Index                                                                                      ...
                                                                                                                                                                                                                                                               )

    %% Section 0: Preliminaries
 
    %% Section 1: Collecting Essential Parameters
        % Level 1: Converting the 'vertical_Cell_of_Instantaneous_Elements_Names' to a 'Vertical Vector'

        % Essential Parameters
                sampling_Frequency                                                                 = vertical_Structure_of_IQ_Component_Parameters. sampling_Frequency;
                bandwidth_Decrement_Factor                                                    = vertical_Structure_of_IQ_Component_Parameters. bandwidth_Decrement_Factor;
                frequency_Multiplication_Factor_for_Modulation                           = vertical_Structure_of_IQ_Component_Parameters. frequency_Multiplication_Factor_for_Modulation;
                do_You_Want_Discretization_and_Digitization_Horizontal_Vector = vertical_Structure_of_IQ_Component_Parameters. do_You_Want_Discretization_and_Digitization_Horizontal_Vector;
                discretizing_Factor                                                                    = vertical_Structure_of_IQ_Component_Parameters. discretizing_Factor;
                number_of_Quantization_Levels                                                  = vertical_Structure_of_IQ_Component_Parameters. number_of_Quantization_Levels;
                minimum_Level_for_Quantization                                                = vertical_Structure_of_IQ_Component_Parameters. minimum_Level_for_Quantization;
                maximum_Level_for_Quantization                                               = vertical_Structure_of_IQ_Component_Parameters. maximum_Level_for_Quantization;
                
        % Calculation of 'IQ Components'               
                input_Single_sub_Region_or_Input_Single_sub_Region_IQ_Component = InPhase_Quadrature_Calculator (      input_Single_sub_Region,                                                                    ...
                                                                                                                                                                                sampling_Frequency,                                                                          ...
                                                                                                                                                                                bandwidth_Decrement_Factor,                                                              ...
                                                                                                                                                                                frequency_Multiplication_Factor_for_Modulation,                                     ...
                                                                                                                                                                                ...                                                                                 
                                                                                                                                                                                do_You_Want_Discretization_and_Digitization_Horizontal_Vector,           ...                                                                      
                                                                                                                                                                                discretizing_Factor,                                                                              ...
                                                                                                                                                                                number_of_Quantization_Levels,                                                            ...
                                                                                                                                                                                minimum_Level_for_Quantization,                                                          ...
                                                                                                                                                                                maximum_Level_for_Quantization);

    %% Section 2: Calling Selected 'Instantaneous Elements' for selected 'sub Region 'Or' IQ component of seb Region'
        vertical_Structure_of_Selected_Instantaneous_Elements_for_Mentioned_Single_sub_Region = Instantaneous_Element_Extractor ( input_Single_sub_Region,                                                                                                    ...  used in: Instantaneous_Element_Extractor / 'selected_Instantaneous_Element_Function'
                                                                                                                                                                                                     input_Single_sub_Region_or_Input_Single_sub_Region_IQ_Component,                                  ...  used in: Instantaneous_Element_Extractor / 'selected_Instantaneous_Element_Function'
                                                                                                                                                                                                     vertical_Cell_of_Instantaneous_Elements_Names                                                                   ... used in: Instantaneous_Element_Extractor                                                                                                                                                                                                     
                                                                                                                                                                                                     );

    %% Section 2: Calling Selected 'Instantaneous Elements' for selected 'sub Region'        
        for index = 1 : size ( vertical_Structure_of_Selected_Instantaneous_Elements_for_Mentioned_Single_sub_Region, 1 )
            input_Single_Instantaneous_Element_Value = [ vertical_Structure_of_Selected_Instantaneous_Elements_for_Mentioned_Single_sub_Region( index, 1 ). instantaneous_Elment_Value ];
            input_Single_Instantaneous_Element_Name = vertical_Structure_of_Selected_Instantaneous_Elements_for_Mentioned_Single_sub_Region( index, 1 ). instantaneous_Elment_Name;
            instantaneous_Element_Name                     = input_Single_Instantaneous_Element_Name;
            vertical_Structure_of_Selected_Characteristics_for_Mentioned_Instantaneous_Elementes_of_Mentioned_Single_sub_Region ( index, 1 ). characteristics_of_Selected_Instantaneous_Element_for_Selected_sub_Region = Characteristic_Extractor ( vertical_Cell_of_Characteristics_Names,                                                ... used in: Characteristic_Extractor
                                                                                                                                                                                                                                                                                                                                                                 input_Single_Instantaneous_Element_Value,                                         ... used in: Characteristic_Extractor / 'selected_Characteristic_Function'
                                                                                                                                                                                                                                                                                                                                                                 device_Index,                                                                                      ...
                                                                                                                                                                                                                                                                                                                                                                 fingerPrint_Index,                                                                                 ...
                                                                                                                                                                                                                                                                                                                                                                 sub_Region_Index,                                                                               ...
                                                                                                                                                                                                                                                                                                                                                                 instantaneous_Element_Name                                                              ...
                                                                                                                                                                                                                                                                                                                                                                 );
        end

end